import { Share } from 'react-native';
import { getStatsInRange, getExerciseBreakdown } from './database';
import type { TFunction } from 'i18next';

interface ReportData {
  period: string;
  first: {
    avgLoudness: number | null;
    avgIntelligibility: number | null;
    exercisesCompleted: number;
    totalDurationSeconds: number;
  };
  second: {
    avgLoudness: number | null;
    avgIntelligibility: number | null;
    exercisesCompleted: number;
    totalDurationSeconds: number;
  };
  breakdown: Record<string, number>;
}

function trendLabel(first: number | null, second: number | null, t: TFunction): string {
  if (first == null || second == null) return t('report.insufficient');
  const diff = second - first;
  if (Math.abs(diff) < 0.05 * Math.max(Math.abs(first), 1)) return t('report.stable');
  return diff > 0 ? t('report.improving') : t('report.declining');
}

export async function generateReport(days: number): Promise<ReportData> {
  const now = new Date();
  const start = new Date(now.getTime() - days * 24 * 60 * 60 * 1000);
  const mid = new Date(now.getTime() - (days / 2) * 24 * 60 * 60 * 1000);

  const startStr = start.toISOString();
  const midStr = mid.toISOString();
  const endStr = now.toISOString();

  const [firstHalf, secondHalf, breakdown] = await Promise.all([
    getStatsInRange(startStr, midStr),
    getStatsInRange(midStr, endStr),
    getExerciseBreakdown(startStr, endStr),
  ]);

  return {
    period: `${start.toLocaleDateString()} – ${now.toLocaleDateString()}`,
    first: {
      avgLoudness: firstHalf.avgLoudness,
      avgIntelligibility: firstHalf.avgIntelligibility,
      exercisesCompleted: firstHalf.exercisesCompleted,
      totalDurationSeconds: firstHalf.totalDurationSeconds,
    },
    second: {
      avgLoudness: secondHalf.avgLoudness,
      avgIntelligibility: secondHalf.avgIntelligibility,
      exercisesCompleted: secondHalf.exercisesCompleted,
      totalDurationSeconds: secondHalf.totalDurationSeconds,
    },
    breakdown,
  };
}

export function formatReportAsText(data: ReportData, t: TFunction): string {
  const lines: string[] = [];

  lines.push(`=== ${t('report.title')} ===`);
  lines.push(`${t('report.period')}: ${data.period}`);
  lines.push('');

  lines.push(`--- ${t('report.summary')} ---`);
  const totalExercises = data.first.exercisesCompleted + data.second.exercisesCompleted;
  const totalMinutes = Math.round(
    (data.first.totalDurationSeconds + data.second.totalDurationSeconds) / 60
  );
  lines.push(`Exercises: ${totalExercises}`);
  lines.push(`Practice time: ${totalMinutes} min`);
  lines.push('');

  lines.push(`--- ${t('report.voiceMetrics')} ---`);

  const loudnessTrend = trendLabel(data.first.avgLoudness, data.second.avgLoudness, t);
  lines.push(
    `Loudness: ${data.second.avgLoudness?.toFixed(1) ?? '–'}x (${loudnessTrend})`
  );

  const clarityTrend = trendLabel(
    data.first.avgIntelligibility,
    data.second.avgIntelligibility,
    t
  );
  lines.push(
    `Clarity: ${data.second.avgIntelligibility != null ? Math.round(data.second.avgIntelligibility) + '%' : '–'} (${clarityTrend})`
  );
  lines.push('');

  lines.push(`--- ${t('report.exerciseBreakdown')} ---`);
  for (const [type, count] of Object.entries(data.breakdown)) {
    lines.push(`${type}: ${count}`);
  }
  lines.push('');
  lines.push('Generated by ParkSpeak');

  return lines.join('\n');
}

export async function shareReport(text: string): Promise<void> {
  await Share.share({ message: text });
}
